plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aiku.daemon'
    compileSdk 34

    defaultConfig {
        applicationId "com.aiku.daemon"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    androidResources {
        noCompress 'txt', 'dat', 'json', 'yaml', 'env'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {}
